### ISSUE TITLE
Extension keeps using an audio stream causing pc to not go to sleep[Bug] 

### ISSUE THREAD

**Issue by 155ac** [FilipePS/Traduzir-paginas-web#802] opened 2024-03-02 07:19 UTC
### Steps To Reproduce

Just install the extension on firefox.

### Expected Result

The extension should not open any audio stream when there is no audio in use.

### Actual Result

The extension opens a audio stream when no audio is use this can be confirmed by executing the command powercfg /requests in cmd, this also cause a problem that the pc never go to sleep because it thinks that ther is a audio being playing when ther is none.

### Operating System

Windows

### Operating System Version

Windows 10 22h2

### Web Browser

Firefox

### Browser Version

Firefox 123.0

### Extension Version

10.0.0.4

### What are you doing?

- [X] I am reporting a bug

**Comment by IgnacioMD** [comment] 2024-03-02 19:48
That happens to me too

**Comment by diegc** [comment] 2024-03-04 09:05
I can confirm that this happens on Android as well, preventing the phone from entering deep sleep and draining the battery. Whether or not there are any open tabs doesn't seem to matter. The only other extensions I have are Video Background Play Fix, Google Search Fixer, Offline QR Code Generator and uBlock Origin, in case it's useful.

**Comment by Wassss** [comment] 2024-03-04 10:05
Same here

With TWP enabled

![enabled](https://github.com/FilipePS/Traduzir-paginas-web/assets/7213383/367d0379-30df-4fd4-9c25-82970c332771)


With TWP disabled

![disabled](https://github.com/FilipePS/Traduzir-paginas-web/assets/7213383/a7082ef1-4efd-4ac5-8ccc-66edfdf0c03d)

**Comment by L0rent** [comment] 2024-03-04 19:06
Same issue here since TWP v10.0.0.4.
Firefox keeps using an audio output hence preventing the PC to go to sleep.
I use Firefox Developer v116.0b8 (64 bits) on Windows 10 22H2 19045.2251 64 bits.
I reverted back to TWP v9.9.0.30 and the issue disappeared.
Otherwise very useful addon.

**Comment by upibis** [comment] 2024-03-04 22:03
same issue. firefox 115 osx 10.13.

resolved by downgrade to v9.9

**Closed** 2024-03-05 05:03 UTC
Labels: bug

**Comment by FilipePS** [comment] 2024-03-05 05:51
As Mozilla always takes time to evaluate new versions of extensions publicly available on [AMO](https://addons.mozilla.org) I used an option to self-host the new version.
You can install it in Firefox through the file [TWP_10.0.1.0_Firefox.xpi](https://github.com/FilipePS/Traduzir-paginas-web/releases/download/v10.0.1.0/TWP_10.0.1.0_Firefox.xpi) available in the release [Version 10.0.1.0](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v10.0.1.0).

**Comment by L0rent** [comment] 2024-03-05 08:37
Thank you Filipe. With v10.0.1.0, powercfg -request dosen't output anything under SYSTEM. Issue seems to be solved.
