### ISSUE TITLE
How I can turn off the Translation cache

### ISSUE THREAD

**Issue by yunyty** [FilipePS/Traduzir-paginas-web#181] opened 2021-06-21 01:08 UTC
Hi Guys,
Sometimes I need to translate pages with almost the same content, and the translation cache reuses the old content before for translation, but in fact, some content has changed which leads to incorrect translation of the content. corpse

How can I disable the translation cache?

**Comment by FilipePS** [comment] 2021-06-21 01:35
Are you sure this is really caused by the translation cache?
If you clear the translation cache does it solve the problem?

The translation cache stores the translation of sentences, for example:
This English sentence "What is the best streaming service?"
Translating into Portuguese is "What is the best streaming service?"

So if the extension has already translated this phrase 1 time, whenever any site has this phrase, the extension will already know how to translate it.

The point is, the translation cache does not distinguish which site you are translating. This also means that if you go to the same site again and the texts have changed, the extension will translate these new texts.

**Comment by yunyty** [comment] 2021-06-21 07:20
I'm not sure it's because of the translation cache or not but you can check this video I made

https://youtu.be/sOpLoyynokM
Please let me know if you don't understand

**Comment by FilipePS** [comment] 2021-06-21 16:09
In this case the problem is in the option to restore the page. Since that text was changed, the extension shouldn't have restored it.

**Comment by yunyty** [comment] 2021-06-21 16:56
Thank you for your reply

I have detailed the description of the video above in the .xlsx file, hope it helps you
[Translate this page.xlsx](https://github.com/FilipePS/Traduzir-paginas-web/files/6688295/Translate.this.page.xlsx)

**Comment by FilipePS** [comment] 2021-06-24 21:49
The fix has already been implemented and will be in the next version.

**Closed by FilipePS** 2021-06-24 21:49 UTC
