### ISSUE TITLE
Can't set target languages...

### ISSUE THREAD

**Issue by Klipperken** [FilipePS/Traduzir-paginas-web#141] opened 2021-04-11 19:51 UTC
**_Hail:_**

_Before anything: I want to thank you for the tool you gave us.
While I have "serious" bugs with it, I DO like the intention, the idea, and -when it DOES work normally- how it operates, the speed, the ease.
For that, I am very grateful, thank you so much!!!_
---------------------------------------------------

**That being said: there ARE issues on my side:**

!!) I have, for God-knows-whatever-reason, THREE target languages.
    This logic eludes me... Why have three ...
    ... and while I can pull out a pull-up with languages, on all three positions, when setting one or another, it does not save.
   The three languages always revert to (in position as I have here):
    Original           English
    Spanish?????    German?????  (=> These are LOCKED, changing the setting results in immediate reset to this "default")

1) Why do I have three!!! target languages?
Folks usually have MORE than enough with 1.
Maybe an option to select the amount of these would be a darn good idea?

2) Why can't I save my setting as per my choice (example: change 2 Target Languages, or have all three in English, so the add-on does not get confused? Trying to alter these is not possible at my side: they are stuck in this position/setting.)

3) Where are these settings stored?
Then I can alter these DIRECTLY the source for the Target Languages, and got it done with, permanently.
Been looking manually for the file that saves these settings, but no luck there: despite having checked all files, none was found with the needed settings.
Scoured through each individual file that had mentioning of a language, still, no luck.
Might be stored elsewhere (been checking ALL the Firefox Profile files).

4) Why not offer a simple "Translate All" to "Target Language: [X]" where [X] is the user's preference?
Instead of of having 1 Source and 3 Target Languages in the Icon-Drop down, have them triggered by a key combination (maybe Alt-T (to trigger translation, standard setting) followed by either Alt-1, Alt-2 or Alt-3 for Target Language of choice, and Alt-0 to have no translation/Original Text?)
This way, the Drop Down menu is no longer needed.
To be safe, allow people to choose their key combination, as some may already use any of these combinations?
That would make things a whole lot easier, for everyone.

5) For some odd reason, the icon in the Firefox Toolbar turns black after a period of usage, as if the add-on turned bad.
No idea WHY it does that, it just does, forcing me to remove the add-on, then reinstall the add-on.
Quite annoying after many times, really...
---------------------------------------------------

I hope to hear for a solution to my problems, kind sir.

Again, thank you so much for the tool, it is of GREAT help (when it works, which it usually does, thank God).
Despite the issues that i have, it IS a wonderful tool, that I suggested to quite a few friends and colleagues.

Kindest regards:
Xogroroth666

**Comment by FilipePS** [comment] 2021-04-11 21:51
1. You cannot repeat the same target languages, they must be different. If you duplicate any, the duplicates will probably be replaced by one of these (English, Spanish, German).

2. There are people who know more languages. Some people wanted an easier way to translate to languages other than their native language. Adding these buttons was my solution.
Using the "More" and "Less" buttons you can control the amount of things that appear in the popup. In addition to the button ![btn](https://user-images.githubusercontent.com/54990796/114322064-a07a4f00-9af4-11eb-8cca-f46c9930ed21.png) you can use the old interface which is simpler, it only has the translate button. 

3. I intend to add more hotkeys in version 9.0

4. Firefox has a native page to change the shortcut keys for extensions.

5. About the icon turning black after a while, I have some questions.
- You use custom themes in Firefox
- Do you use the windows operating system? Do you use native dark mode?
- When the icon turns black you notice some other difference in Firefox, can you tell when this happens?

**Comment by Klipperken** [comment] 2021-04-12 16:28
Greetings:

Thank you very much for your reply, sir.

questions => answers:
1) No sir, basic ones.
2) I turned Dark Mode on yesterday, lately I have headaches from prolonged
PC usage... the issue is from earlier.
3)No other behaviour noticed, sir. Only that icon turning black, becoming
non-responsive. Reinstallation fixes this.

If you need more information, please ask...

Kindest regards:
Ben

**Comment by FilipePS** [comment] 2021-04-12 17:53
1 - What is your operating system?
2 - What version of your Firefox?
3 - What version of the extension?
4 - Did this problem always occur, or did it occur after any specific version of the extension?
5 - When you said _"becoming
non-responsive"_ meant that the extension was slow?
6 - Does this problem happen at random, or can you tell me how to reproduce it?

**Comment by Klipperken** [comment] 2021-04-12 18:26
Hail, sir:

1) Win 10 x64, 20h2, 19042.867
2) 87.0 x64
3) 8.9.3
4) Not after a certain version of extension, but after this very Win build,
oddly
5) Non-responsive = not doing a darn thing, it becomes a dead, black "icon"
(well, it IS there, in a way, while not being there at all, like an empty
link, so to speak)
6) Random

Want more information, good sir?
Just ask.   :)

**Comment by FilipePS** [comment] 2021-04-12 19:06
If it was right after a windows update, I suppose it is a windows bug. For now I don't think I can do anything.

About your other questions. I was able to clarify your doubts, or do you still have problems?

**Comment by FilipePS** [comment] 2021-04-12 19:23
Can you tell me if this problem occurs after translating a specific website?

Does translating using Alt + T or translating selected text work?

**Comment by Klipperken** [comment] 2021-04-12 19:29
Hail sir:

Well, good sir, it would be spliffy if i could "turn off" two of the three
Target Languages...
I had issues by them jumping from one to another for some odd reason, which
I still have not figured  out.
Hence the: if only I could set all three to English, indicating they jumped
irregularly to another one.
I tried with keys: maybe a certain key press does it, but no, it dares
happening while just reading a text, that it suddenly turns German or
Spanish.
So, the jump in language is not key-bound, but like my icon turning "dead",
it's very random.

IF I could edit the base file, FORCING all three to be English, then it
would not make a difference, since, that is my prime target language (even
though I am Flemish, it is not Dutch, oddly).

If you would be so kind as to tell me where this base command line is...?
:)

OR that you would add an option to turn one or two target languages off?

Ah, the "simplified version" also jumps between English, German and Spanish.
Hence that option is, for me, also out of the window...   :(

Bizarre, now that you mentioned an external force screwing with the
Translator.... I wonder which that could be?

Kindest regards:
Ben

**Comment by FilipePS** [comment] 2021-04-12 20:13
> I had issues by them jumping from one to another for some odd reason, which I still have not figured out. 

Before version 8.7, whenever you click on one of the translate buttons, this button becomes the first of the three. So their order changed, however from version 8.7 they do not change positions alone. Except when you change the target languages. 
I cannot imagine how this could happen in the current versions. I did some tests and it doesn't seem to happen anymore.

> If you would be so kind as to tell me where this base command line is...?
Somewhere in the _`lib/config.js`_ file

> Ah, the "simplified version" also jumps between English, German and Spanish.
Are you talking about the interface that only has the "Translate" button?

> Hence that option is, for me, also out of the window...   :(
I didn't understand what you meant

> Bizarre, now that you mentioned an external force screwing with the
> Translator.... I wonder which that could be?

Maybe because of some bad optimization of the extension, and I performed poorly on the computer. Perhaps a website can overload the extension and cause the bug. That's why I asked.

If you can provide a video showing these problems it would help a lot.



About the problem the icon is black and nothing in the extension works.
It reminded me that in the last few weeks, while I was testing the extension, I had a similar problem. In this case, the extension was manually loaded through the "about: debugging" page.
While reloading the extension to test new changes, there were times when the extension would stop working, even if I remove the extension and upload it again it doesn't work. The only solution was to close Firefox and open it again.

**Comment by FilipePS** [comment] 2022-10-26 15:10
I'm closing this issue. If you have any more problems, please create a new issue.

**Closed by FilipePS** 2022-10-26 15:10 UTC
