### ISSUE TITLE
Translate when orriginal language unknown

### ISSUE THREAD

**Issue by PhantumPhysics** [FilipePS/Traduzir-paginas-web#113] opened 2021-03-09 08:11 UTC
Hi,

I have noticed now (I think since the last update) that now many pages are showing an unknown language and no way to translate.  Could you please fix it so you can specify a language and force translation?  The source language in my case is usually Finnish, I don't know why it is sometimes not detected now when I am sure it used to be detected most of the time

Awesome extension, a lifesaver for me after I moved from Chrome to Firefox!

**Comment by FilipePS** [comment] 2021-03-09 11:57
What target language do you use? I noticed that this only happens in some languages

**Comment by PhantumPhysics** [comment] 2021-03-09 12:03
Target language English.  I have selected other languages Swedish and still does not translate.  Maybe some button to force selection of source language?

**Comment by PhantumPhysics** [comment] 2021-03-09 12:08
Actually, it seems to work now on at least one of the pages where it was not working this morning...

**Comment by FilipePS** [comment] 2021-03-09 12:24
Using the instructions #107 , I managed to reproduce the problem.
Analyzing the requests that the extension made to the Google server, I realized that Google translated it wrong, it does not return to respond in the format that it should. This also happened in the old versions of the extension. It did not appear "undefined" on the page, because before the extension did not try to translate using invalid information received from Google, it kept the original language. This commit will avoid showing this "undefined" text
https://github.com/FilipePS/Traduzir-paginas-web/commit/50b63b8dfaf16469c2023ddc6865bc572951606b

**Comment by PhantumPhysics** [comment] 2021-03-09 12:44
This still will not let the page be translated though?
For example, this page does not translate but lists undefined (translation to English)
https://www.rakentaja.fi/keskustelut/185981/puukarmisia_ikkunoita_vanhaan_taloon
but not on other pages in the same website
https://www.rakentaja.fi/keskustelut/187017/ikkunakarmien_tiivistys

If the problem is that the language is not detected then can the user manually set the language for a page?

**Comment by FilipePS** [comment] 2021-03-09 12:53
In order not to appear "undefined" the problem has already been fixed, and will be in the next version.

**Comment by FilipePS** [comment] 2021-03-09 14:07
Specifying the language of the page does not solve the problem of parts of it not being translated.
I made some commits that should avoid this problem and better translate a little on some sites.
https://github.com/FilipePS/Traduzir-paginas-web/commit/e317c3ba2dcdf1d002d95e08ffc20aa34d087389
https://github.com/FilipePS/Traduzir-paginas-web/commit/11d2e2d8912def805b0507c8980268ec03269c21

**Closed** 2021-03-09 14:07 UTC
